### ISSUE TITLE
Navbar starts open (moved)

### ISSUE THREAD

**Issue by ametom** [Darkshivers/portfolio#3]
Loading the page in mobile view has the navbar loaded expanded, but clicking the button to close it "expands" it again, a third click closes it.
This is because of the navbar html being faulty somewhere. I spent a while looking at the documentation and examples and can't figure out why, I suggest you rewrite the navbar.
This one works http://jsfiddle.net/52VtD/7046/

**Comment by Darkshivers** [comment]
Doesn't seem to work what so ever currently. Maybe youre right.
